-- book2-vocab-5to13-migration.sql
-- 時代華語 Book 2 Lessons 5-13 Vocabulary
-- Generated: 2026-04-12

-- ============================================================
-- UPDATE LESSON TITLES
-- ============================================================
UPDATE lessons SET title_zh = '歡迎到我家來玩' WHERE id = 'book2-lesson05';
UPDATE lessons SET title_zh = '我們去KTV唱歌吧！' WHERE id = 'book2-lesson06';
UPDATE lessons SET title_zh = '坐火車到花蓮去旅行' WHERE id = 'book2-lesson07';
UPDATE lessons SET title_zh = '請給我貼紙，我要換史努比！' WHERE id = 'book2-lesson08';
UPDATE lessons SET title_zh = '你怕考試嗎？' WHERE id = 'book2-lesson09';
UPDATE lessons SET title_zh = '下課後一起去健身吧！' WHERE id = 'book2-lesson10';
UPDATE lessons SET title_zh = '你想參加哪一個社團？' WHERE id = 'book2-lesson11';
UPDATE lessons SET title_zh = '小職員? 大老闆?' WHERE id = 'book2-lesson12';
UPDATE lessons SET title_zh = '我要買筆電' WHERE id = 'book2-lesson13';

-- ============================================================
-- LESSON 05: 歡迎到我家來玩
-- ============================================================
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson05', 1, '社區', 'shè qū', 'コミュニティ・団地', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson05', 2, '白天', 'bái tiān', '昼間・日中', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson05', 3, '被', 'bèi', '〜された（受身）', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson05', 4, '小偷', 'xiǎo tōu', '泥棒', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson05', 5, '偷', 'tōu', '盗む', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson05', 6, '負責', 'fù zé', '責任を負う', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson05', 7, '安全', 'ān quán', '安全', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson05', 8, '大門', 'dà mén', '正門・玄関', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson05', 9, '草地', 'cǎo dì', '芝生・草原', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson05', 10, '辦', 'bàn', '行う・手続きする', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson05', 11, '晴天', 'qíng tiān', '晴れの日', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson05', 12, '野餐', 'yě cān', 'ピクニック', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson05', 13, '餐', 'cān', '食事・食', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson05', 14, '露營', 'lù yíng', 'キャンプ', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson05', 15, '雲', 'yún', '雲', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson05', 16, '躺', 'tǎng', '横になる', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson05', 17, '星星', 'xīng xīng', '星', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson05', 18, '感覺', 'gǎn jué', '感じ・感覚', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson05', 19, '輕鬆', 'qīng sōng', 'リラックスした', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson05', 20, '睡著', 'shuì zháo', '寝つく・眠る', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson05', 21, '陽光', 'yáng guāng', '日差し・太陽の光', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson05', 22, '香味', 'xiāng wèi', '香り・良い香り', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson05', 23, '座', 'zuò', '〜棟（量詞）', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson05', 24, '球場', 'qiú chǎng', '球技場・コート', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson05', 25, '游泳池', 'yóu yǒng chí', 'プール', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson05', 26, '校友', 'xiào yǒu', '卒業生・校友', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson05', 27, '只要', 'zhǐ yào', '〜さえすれば', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson05', 28, '請客', 'qǐng kè', 'おごる・招待する', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson05', 29, '牛排', 'niú pái', 'ステーキ', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson05', 30, '紅綠燈', 'hóng lǜ dēng', '信号機', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson05', 31, '幸福', 'xìng fú', '幸せ・幸福', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson05', 32, '市', 'shì', '市・都市', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson05', 33, '郊區', 'jiāo qū', '郊外', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson05', 34, '長大', 'zhǎng dà', '成長する・大きくなる', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson05', 35, '巴士', 'bā shì', 'バス', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson05', 36, '還好', 'hái hǎo', 'まあまあ・まだまし', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson05', 37, '班', 'bān', 'クラス・便（量詞）', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson05', 38, '要不然', 'yào bu rán', 'でなければ・さもないと', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson05', 39, '麻煩', 'má fán', '面倒・迷惑', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson05', 40, '經過', 'jīng guò', '通り過ぎる・経由する', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson05', 41, '人員', 'rén yuán', 'スタッフ・要員', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson05', 42, '花園', 'huā yuán', '庭園・花園', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson05', 43, '新鮮', 'xīn xiān', '新鮮・フレッシュ', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson05', 44, '像', 'xiàng', '〜のようだ・似る', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson05', 45, '書店', 'shū diàn', '本屋', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson05', 46, '停車場', 'tíng chē chǎng', '駐車場', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson05', 47, '停', 'tíng', '止まる・停車する', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson05', 48, '圓', 'yuán', '丸い・円', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson05', 49, '月亮', 'yuè liàng', '月', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson05', 50, '月餅', 'yuè bǐng', '月餅', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson05', 51, '餅', 'bǐng', '餅・焼き菓子', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson05', 52, '真是', 'zhēn shì', '本当に〜だ', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson05', 53, '中秋節', 'zhōng qiū jié', '中秋節', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson05', 54, '台北市', 'tái běi shì', '台北市', '[]');

-- ============================================================
-- LESSON 06: 我們去KTV唱歌吧！
-- ============================================================
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson06', 1, '不同', 'bù tóng', '異なる・違う', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson06', 2, '差不多', 'chà bu duō', 'だいたい・ほぼ同じ', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson06', 3, '不過', 'bú guò', 'しかし・ただし', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson06', 4, '目的', 'mù dì', '目的', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson06', 5, '合唱', 'hé chàng', '合唱する', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson06', 6, '錯', 'cuò', '間違い・悪い', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson06', 7, '隔壁', 'gé bì', '隣・隣室', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson06', 8, '跳', 'tiào', '跳ぶ・踊る', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson06', 9, '地板', 'dì bǎn', '床（ゆか）', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson06', 10, '動', 'dòng', '動く・動かす', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson06', 11, '學會', 'xué huì', '習得する・覚える', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson06', 12, '歌曲', 'gē qǔ', '歌・楽曲', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson06', 13, '拿手', 'ná shǒu', '得意・上手', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson06', 14, '歌星', 'gē xīng', '歌手・スター', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson06', 15, '機器', 'jī qì', '機器・機械', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson06', 16, '分數', 'fēn shù', '点数・スコア', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson06', 17, '可怕', 'kě pà', '恐ろしい・怖い', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson06', 18, '弄錯', 'nòng cuò', '間違える', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson06', 19, '差', 'chà', '劣る・悪い', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson06', 20, '低', 'dī', '低い', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson06', 21, '方法', 'fāng fǎ', '方法・やり方', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson06', 22, '興奮', 'xīng fèn', '興奮する', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson06', 23, '地', 'de', '〜に・〜と（副詞化）', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson06', 24, '棒', 'bàng', 'すごい・素晴らしい', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson06', 25, '好好/好好兒', 'hǎo hǎo / hǎo hāor', 'しっかり・きちんと', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson06', 26, '想到', 'xiǎng dào', '思いつく・思い出す', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson06', 27, '香水', 'xiāng shuǐ', '香水', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson06', 28, '束', 'shù', '〜束（量詞）', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson06', 29, '玫瑰', 'méi guī', 'バラ', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson06', 30, '別', 'bié', '〜するな（禁止）', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson06', 31, '罐', 'guàn', '缶・〜缶（量詞）', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson06', 32, '啤酒', 'pí jiǔ', 'ビール', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson06', 33, '喔', 'ō', 'ああ・へえ（感嘆詞）', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson06', 34, '消息', 'xiāo xī', 'ニュース・知らせ', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson06', 35, 'KTV', 'K T V', 'カラオケボックス', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson06', 36, '吃到飽', 'chī dào bǎo', '食べ放題', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson06', 37, '打分數', 'dǎ fēn shù', '採点する', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson06', 38, '不少', 'bù shǎo', 'かなり多い・少なくない', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson06', 39, '隨時', 'suí shí', 'いつでも', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson06', 40, '前', 'qián', '前・以前', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson06', 41, '後', 'hòu', '後・以降', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson06', 42, '才', 'cái', 'やっと・〜してから初めて', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson06', 43, '假日', 'jià rì', '休日・祝日', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson06', 44, '平日', 'píng rì', '平日', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson06', 45, '客滿', 'kè mǎn', '満員・満席', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson06', 46, '利用', 'lì yòng', '利用する', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson06', 47, '時', 'shí', '〜のとき', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson06', 48, '省錢', 'shěng qián', 'お金を節約する', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson06', 49, '特色', 'tè sè', '特色・特徴', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson06', 50, '各式各樣', 'gè shì gè yàng', 'さまざまな種類', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson06', 51, '不必', 'bù bì', '〜しなくてよい', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson06', 52, '樂器', 'yuè qì', '楽器', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson06', 53, '讓', 'ràng', '〜させる・譲る', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson06', 54, '生氣', 'shēng qì', '怒る', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson06', 55, '傷心', 'shāng xīn', '悲しむ・傷つく', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson06', 56, '哭', 'kū', '泣く', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson06', 57, '選擇', 'xuǎn zé', '選択する・選ぶ', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson06', 58, '卡拉OK', 'kǎ lā OK', 'カラオケ', '[]');

-- ============================================================
-- LESSON 07: 坐火車到花蓮去旅行
-- ============================================================
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson07', 1, '前年', 'qián nián', '一昨年', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson07', 2, '包', 'bāo', '包む・パック', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson07', 3, '當地', 'dāng dì', '現地・地元', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson07', 4, '名產', 'míng chǎn', '名産品・特産品', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson07', 5, '明信片', 'míng xìn piàn', 'はがき・ポストカード', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson07', 6, '訂', 'dìng', '予約する・注文する', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson07', 7, '免費', 'miǎn fèi', '無料', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson07', 8, '無線網路', 'wú xiàn wǎng lù', 'Wi-Fi・無線LAN', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson07', 9, '美麗', 'měi lì', '美しい', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson07', 10, '美', 'měi', '美しい・美', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson07', 11, '毛', 'máo', '毛・羽毛', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson07', 12, '讓', 'ràng', '〜させる・譲る', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson07', 13, '正在', 'zhèng zài', '〜している（進行中）', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson07', 14, '公路', 'gōng lù', '幹線道路・国道', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson07', 15, '石頭', 'shí tóu', '石', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson07', 16, '掉', 'diào', '落ちる・落とす', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson07', 17, '下來', 'xià lái', '降りてくる', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson07', 18, '一下子/一下', 'yī xià zi / yī xià', 'すぐに・一瞬で', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson07', 19, '光', 'guāng', '光・だけ', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson07', 20, '鐵路', 'tiě lù', '鉄道', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson07', 21, '鐵', 'tiě', '鉄', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson07', 22, '網頁', 'wǎng yè', 'ウェブページ', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson07', 23, '訂位', 'dìng wèi', '席を予約する', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson07', 24, '底', 'dǐ', '底・末', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson07', 25, '出發', 'chū fā', '出発する', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson07', 26, '國家公園', 'guó jiā gōng yuán', '国立公園', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson07', 27, '爬', 'pá', '登る・這う', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson07', 28, '座位', 'zuò wèi', '座席・席', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson07', 29, '位子', 'wèi zi', '席・場所', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson07', 30, '記', 'jì', '記録する・覚える', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson07', 31, '日期', 'rì qī', '日付', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson07', 32, '民宿', 'mín sù', '民宿・B&B', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson07', 33, '蘇花公路', 'sū huā gōng lù', '蘇花公路', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson07', 34, '台灣鐵路局/台鐵', 'tái wān tiě lù jú / tái tiě', '台湾鉄道（台鐵）', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson07', 35, '太魯閣號', 'tài lǔ gé hào', 'タロコ号（特急）', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson07', 36, '掉下來', 'diào xià lái', '落ちてくる', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson07', 37, '記下來', 'jì xià lái', 'メモする・書き留める', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson07', 38, '計畫/劃', 'jì huà', '計画する', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson07', 39, '春假', 'chūn jià', '春休み', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson07', 40, '森林', 'sēn lín', '森林・森', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson07', 41, '走走', 'zǒu zǒu', 'ぶらぶらする・散歩する', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson07', 42, '草', 'cǎo', '草', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson07', 43, '暖和', 'nuǎn huo', '暖かい', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson07', 44, '行李', 'xíng lǐ', '荷物・スーツケース', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson07', 45, '大衣', 'dà yī', 'コート・外套', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson07', 46, '外套', 'wài tào', 'ジャケット・上着', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson07', 47, '雨衣', 'yǔ yī', 'レインコート', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson07', 48, '內衣', 'nèi yī', '下着', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson07', 49, '團體', 'tuán tǐ', '団体・グループ', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson07', 50, '自由', 'zì yóu', '自由', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson07', 51, '趕', 'gǎn', '急ぐ・間に合わせる', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson07', 52, '當天', 'dāng tiān', '当日・その日', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson07', 53, '留', 'liú', '残る・留まる', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson07', 54, '國內', 'guó nèi', '国内', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson07', 55, '不少', 'bù shǎo', 'かなり多い・少なくない', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson07', 56, '信用卡', 'xìn yòng kǎ', 'クレジットカード', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson07', 57, '放心', 'fàng xīn', '安心する', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson07', 58, '趁(著)', 'chèn (zhe)', '〜に乗じて・〜のうちに', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson07', 59, '樣子', 'yàng zi', '様子・外見', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson07', 60, '成功', 'chéng gōng', '成功する', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson07', 61, '機票', 'jī piào', '航空券', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson07', 62, '阿里山', 'ā lǐ shān', '阿里山', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson07', 63, '嘉義', 'jiā yì', '嘉義', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson07', 64, '阿里山小火車', 'ā lǐ shān xiǎo huǒ chē', '阿里山森林鉄道', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson07', 65, '遊樂區', 'yóu lè qū', 'レジャーエリア', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson07', 66, '內衣褲', 'nèi yī kù', '下着・肌着とパンツ', '[]');

-- ============================================================
-- LESSON 08: 請給我貼紙，我要換史努比！
-- ============================================================
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson08', 1, '貼紙', 'tiē zhǐ', 'シール・ステッカー', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson08', 2, '貼', 'tiē', '貼る', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson08', 3, '豆漿', 'dòu jiāng', '豆乳', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson08', 4, '盒子', 'hé zi', '箱・ボックス', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson08', 5, '盒', 'hé', '箱・〜箱（量詞）', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson08', 6, '店員', 'diàn yuán', '店員', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson08', 7, '差', 'chà', '足りない・不足', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson08', 8, '娃娃', 'wá wa', '人形・ぬいぐるみ', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson08', 9, '它', 'tā', 'それ・あれ（物）', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson08', 10, '它們', 'tā men', 'それら（物）', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson08', 11, '滿', 'mǎn', '満杯・満ちる', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson08', 12, '連', 'lián', '〜さえも', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson08', 13, '得到', 'dé dào', '手に入れる・得る', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson08', 14, '那樣', 'nà yàng', 'そのように・ああいう', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson08', 15, '海報', 'hǎi bào', 'ポスター', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson08', 16, '吸引', 'xī yǐn', '引きつける・惹きつける', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson08', 17, '商人', 'shāng rén', '商人・ビジネスマン', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson08', 18, '心理', 'xīn lǐ', '心理・気持ち', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson08', 19, '尺', 'chǐ', '定規・ものさし', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson08', 20, '牙刷', 'yá shuā', '歯ブラシ', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson08', 21, '卡通人物', 'kǎ tōng rén wù', 'アニメキャラクター', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson08', 22, '卡通', 'kǎ tōng', 'アニメ・漫画', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson08', 23, '人物', 'rén wù', '人物・キャラクター', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson08', 24, '喜愛', 'xǐ ài', '好む・愛好する', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson08', 25, '只好', 'zhǐ hǎo', '仕方なく〜するしかない', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson08', 26, '花', 'huā', 'お金・時間を使う', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson08', 27, '開始', 'kāi shǐ', '始まる・始める', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson08', 28, '為了', 'wèi le', 'ために', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson08', 29, '顧客', 'gù kè', '顧客・お客さん', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson08', 30, '變成', 'biàn chéng', '〜になる・変わる', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson08', 31, '所有', 'suǒ yǒu', 'すべての・全ての', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson08', 32, '這樣', 'zhè yàng', 'このように・こういう', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson08', 33, '那樣', 'nà yàng', 'そのように・あのように', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson08', 34, '類', 'lèi', '種類・カテゴリ', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson08', 35, '影響', 'yǐng xiǎng', '影響する・影響', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson08', 36, '增加', 'zēng jiā', '増加する・増える', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson08', 37, '紀念', 'jì niàn', '記念する・記念', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson08', 38, '史努比', 'shǐ nǔ bǐ', 'スヌーピー', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson08', 39, '一開始', 'yī kāi shǐ', '最初から・初めは', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson08', 40, '想出(來)', 'xiǎng chū (lái)', '思いつく・考え出す', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson08', 41, '吸引力', 'xī yǐn lì', '魅力・引力', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson08', 42, '變', 'biàn', '変わる・変える', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson08', 43, '打瞌睡', 'dǎ kē shuì', 'うとうとする・居眠りする', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson08', 44, '以為', 'yǐ wéi', '〜と思っていた（誤解）', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson08', 45, '發生', 'fā shēng', '発生する・起こる', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson08', 46, '連續劇', 'lián xù jù', '連続ドラマ', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson08', 47, '關係', 'guān xi', '関係・つながり', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson08', 48, '韓式', 'hán shì', '韓国式・韓国風', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson08', 49, '服裝', 'fú zhuāng', '服装・ファッション', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson08', 50, '帽子', 'mào zi', '帽子', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson08', 51, '毛衣', 'máo yī', 'セーター', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson08', 52, '化妝品', 'huà zhuāng pǐn', '化粧品', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson08', 53, '商品', 'shāng pǐn', '商品・製品', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson08', 54, '化妝', 'huà zhuāng', '化粧する', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson08', 55, '保養', 'bǎo yǎng', 'スキンケア・メンテナンス', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson08', 56, '後年', 'hòu nián', '再来年', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson08', 57, '遊學', 'yóu xué', '語学留学・短期留学', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson08', 58, '影集', 'yǐng jí', 'ドラマシリーズ', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson08', 59, '平常', 'píng cháng', 'ふだん・普通', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson08', 60, '方式', 'fāng shì', '方式・やり方', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson08', 61, '改變', 'gǎi biàn', '変化する・変える', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson08', 62, '韓流', 'hán liú', '韓流', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson08', 63, '韓劇', 'hán jù', '韓国ドラマ', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson08', 64, '日劇', 'rì jù', '日本ドラマ', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson08', 65, '愛上', 'ài shàng', '好きになる・惚れる', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson08', 66, '跟上', 'gēn shàng', '追いつく・ついていく', '[]');

-- ============================================================
-- LESSON 09: 你怕考試嗎？
-- ============================================================
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson09', 1, '鐘', 'zhōng', '時計・ベル', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson09', 2, '到', 'dào', '到着する・〜まで', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson09', 3, '翻', 'fān', 'めくる・ひっくり返す', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson09', 4, '頁', 'yè', 'ページ', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson09', 5, '三明治', 'sān míng zhì', 'サンドイッチ', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson09', 6, '門', 'mén', 'ドア・門', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson09', 7, '課堂', 'kè táng', '授業中・教室', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson09', 8, '期末', 'qī mò', '学期末', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson09', 9, '口試', 'kǒu shì', '口頭試験', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson09', 10, '篇', 'piān', '〜篇（量詞・文章）', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson09', 11, '作文', 'zuò wén', '作文', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson09', 12, '用功', 'yòng gōng', '勉強する・努力する', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson09', 13, '當', 'dāng', '〜になる・担当する', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson09', 14, '修', 'xiū', '履修する・修理する', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson09', 15, '教授', 'jiào shòu', '教授', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson09', 16, '知識', 'zhī shì', '知識', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson09', 17, '豐富', 'fēng fù', '豊かな・豊富な', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson09', 18, '教法', 'jiào fǎ', '教え方・指導法', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson09', 19, '系', 'xì', '学科・学部', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson09', 20, '文法', 'wén fǎ', '文法', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson09', 21, '筆試', 'bǐ shì', '筆記試験', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson09', 22, '交', 'jiāo', '提出する・渡す', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson09', 23, '報告', 'bào gào', 'レポート・報告', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson09', 24, '認真', 'rèn zhēn', '真剣な・まじめな', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson09', 25, '字典', 'zì diǎn', '辞書・字典', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson09', 26, '翻譯', 'fān yì', '翻訳する', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson09', 27, '翻', 'fān', 'めくる・翻訳する', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson09', 28, '題', 'tí', '問題・〜問（量詞）', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson09', 29, '努力', 'nǔ lì', '努力する', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson09', 30, '能力', 'néng lì', '能力・実力', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson09', 31, '將來', 'jiāng lái', '将来', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson09', 32, '夠', 'gòu', '十分・足りる', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson09', 33, '加油', 'jiā yóu', '頑張れ・ファイト', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson09', 34, '義大利', 'yì dà lì', 'イタリア', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson09', 35, '期末考', 'qī mò kǎo', '期末試験', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson09', 36, '交換', 'jiāo huàn', '交換する', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson09', 37, '中心', 'zhōng xīn', 'センター・中心', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson09', 38, '漢語', 'hàn yǔ', '中国語・漢語', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson09', 39, '漢字', 'hàn zì', '漢字', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson09', 40, '聲調', 'shēng diào', '声調・トーン', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson09', 41, '部分/份', 'bù fèn', '部分・パート', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson09', 42, '生字', 'shēng zì', '新出単語', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson09', 43, '清楚', 'qīng chǔ', 'はっきりした・明確な', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson09', 44, '造句', 'zào jù', '例文を作る', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson09', 45, '報告', 'bào gào', 'レポート・発表', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson09', 46, '表達', 'biǎo dá', '表現する・伝える', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson09', 47, '意見', 'yì jiàn', '意見', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson09', 48, '錯字', 'cuò zì', '誤字・スペルミス', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson09', 49, '交', 'jiāo', '提出する', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson09', 50, '語法', 'yǔ fǎ', '文法・語法', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson09', 51, '借', 'jiè', '借りる・貸す', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson09', 52, '還', 'huán', '返す', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson09', 53, '迷路', 'mí lù', '道に迷う', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson09', 54, '感動', 'gǎn dòng', '感動する', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson09', 55, '煩惱', 'fán nǎo', '悩み・悩む', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson09', 56, '建議', 'jiàn yì', '提案する・アドバイス', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson09', 57, '華語(文)中心', 'huá yǔ (wén) zhōng xīn', '中国語センター', '[]');

-- ============================================================
-- LESSON 10: 下課後一起去健身吧！
-- ============================================================
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson10', 1, '健身', 'jiàn shēn', 'フィットネス・運動', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson10', 2, '頭痛', 'tóu tòng', '頭痛', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson10', 3, '拉肚子', 'lā dù zi', 'お腹を下す', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson10', 4, '看病', 'kàn bìng', '診察を受ける・医者に行く', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson10', 5, '老是', 'lǎo shì', 'いつも・しょっちゅう', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson10', 6, '改', 'gǎi', '改める・直す', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson10', 7, '健身房', 'jiàn shēn fáng', 'ジム・フィットネスセンター', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson10', 8, '從小', 'cóng xiǎo', '子どもの頃から', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson10', 9, '操場', 'cāo chǎng', '校庭・グラウンド', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson10', 10, '體育', 'tǐ yù', '体育', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson10', 11, '腿', 'tuǐ', '脚・太もも', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson10', 12, '脖子', 'bó zi', '首', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson10', 13, '死', 'sǐ', '死ぬ・ひどく（強調）', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson10', 14, '誇張', 'kuā zhāng', '大げさな', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson10', 15, '叫', 'jiào', '呼ぶ・叫ぶ', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson10', 16, '救護車', 'jiù hù chē', '救急車', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson10', 17, '送', 'sòng', '送る・届ける', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson10', 18, '救命', 'jiù mìng', '助けて！', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson10', 19, '救', 'jiù', '救う・助ける', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson10', 20, '照', 'zhào', '照らす・従う', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson10', 21, '教練', 'jiào liàn', 'コーチ・トレーナー', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson10', 22, '變', 'biàn', '変わる・なる', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson10', 23, '體重', 'tǐ zhòng', '体重', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson10', 24, '減', 'jiǎn', '減る・減らす', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson10', 25, '下', 'xià', '下・降りる', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson10', 26, '年紀', 'nián jì', '年齢・年', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson10', 27, '男人', 'nán rén', '男性・男', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson10', 28, '女人', 'nǚ rén', '女性・女', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson10', 29, '老人', 'lǎo rén', '高齢者・お年寄り', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson10', 30, '青菜', 'qīng cài', '野菜・青菜', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson10', 31, '漢堡', 'hàn bǎo', 'ハンバーガー', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson10', 32, '薯條', 'shǔ tiáo', 'フライドポテト', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson10', 33, '餅乾', 'bǐng gān', 'クッキー・ビスケット', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson10', 34, '飲食', 'yǐn shí', '飲食・食生活', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson10', 35, '油', 'yóu', '油・脂っこい', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson10', 36, '鹽', 'yán', '塩', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson10', 37, '可樂', 'kě lè', 'コーラ', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson10', 38, '開水', 'kāi shuǐ', '白湯・沸かした水', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson10', 39, '來不及', 'lái bu jí', '間に合わない', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson10', 40, '來得及', 'lái de jí', '間に合う', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson10', 41, '三餐', 'sān cān', '三食・一日三食', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson10', 42, '餐', 'cān', '食事', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson10', 43, '國王', 'guó wáng', '王様・国王', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson10', 44, '到底', 'dào dǐ', '一体・結局', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson10', 45, '活', 'huó', '生きる・活', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson10', 46, '訓練', 'xùn liàn', 'トレーニング・訓練', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson10', 47, '慢跑', 'màn pǎo', 'ジョギング', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson10', 48, '開夜車', 'kāi yè chē', '夜遅くまで勉強する', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson10', 49, '好處', 'hǎo chù', 'メリット・利点', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson10', 50, '壞處', 'huài chù', 'デメリット・欠点', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson10', 51, '或許', 'huò xǔ', 'もしかして・おそらく', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson10', 52, '經常', 'jīng cháng', 'よく・頻繁に', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson10', 53, '體力', 'tǐ lì', '体力', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson10', 54, '力', 'lì', '力・パワー', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson10', 55, '精神', 'jīng shén', '元気・精神', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson10', 56, '幫助', 'bāng zhù', '助ける・手伝う', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson10', 57, '改善', 'gǎi shàn', '改善する', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson10', 58, '情況', 'qíng kuàng', '状況・状態', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson10', 59, '讓', 'ràng', '〜させる', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson10', 60, '堂', 'táng', '〜コマ（授業の量詞）', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson10', 61, '繼續', 'jì xù', '続ける・継続する', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson10', 62, '建議', 'jiàn yì', 'アドバイス・提案', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson10', 63, '病人', 'bìng rén', '病人・患者', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson10', 64, '病', 'bìng', '病気・病む', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson10', 65, '恢復', 'huī fù', '回復する', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson10', 66, '活動', 'huó dòng', '活動・イベント', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson10', 67, '難過', 'nán guò', '悲しい・つらい', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson10', 68, '脫', 'tuō', '脱ぐ', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson10', 69, '牛仔褲', 'niú zǎi kù', 'ジーンズ', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson10', 70, '運動服', 'yùn dòng fú', 'スポーツウェア', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson10', 71, '的話', 'de huà', '〜なら・〜であれば', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson10', 72, '睡午覺', 'shuì wǔ jiào', '昼寝をする', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson10', 73, '脫下', 'tuō xià', '脱ぎ下ろす', '[]');

-- ============================================================
-- LESSON 11: 你想參加哪一個社團？
-- ============================================================
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson11', 1, '社團', 'shè tuán', 'クラブ・サークル', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson11', 2, '校園', 'xiào yuán', 'キャンパス・学校の敷地', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson11', 3, '擺', 'bǎi', '並べる・置く', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson11', 4, '攤子', 'tān zi', '屋台・出店', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson11', 5, '社員', 'shè yuán', 'メンバー・部員', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson11', 6, '遍', 'biàn', '〜回（動作の量詞）', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson11', 7, '選擇', 'xuǎn zé', '選択する・選ぶ', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson11', 8, '立刻', 'lì kè', 'すぐに・直ちに', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson11', 9, '鋼琴', 'gāng qín', 'ピアノ', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson11', 10, '功夫', 'gōng fu', '武術・カンフー', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson11', 11, '感興趣', 'gǎn xìng qù', '興味がある', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson11', 12, '藝術', 'yì shù', '芸術', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson11', 13, '嘛', 'ma', '〜じゃないか（語気助詞）', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson11', 14, '厲害', 'lì hài', 'すごい・強い', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson11', 15, '保護', 'bǎo hù', '保護する・守る', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson11', 16, '勇敢', 'yǒng gǎn', '勇敢な・勇気ある', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson11', 17, '吉他', 'jí tā', 'ギター', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson11', 18, '愛心', 'ài xīn', '思いやり・愛の心', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson11', 19, '服務', 'fú wù', 'サービス・奉仕する', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson11', 20, '技巧', 'jì qiǎo', 'テクニック・技術', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson11', 21, '複習', 'fù xí', '復習する', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson11', 22, '同', 'tóng', '同じ・一緒に', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson11', 23, '地球', 'dì qiú', '地球', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson11', 24, '互相', 'hù xiāng', 'お互いに', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson11', 25, '戀愛', 'liàn ài', '恋愛する', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson11', 26, '中華文化', 'zhōng huá wén huà', '中華文化', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson11', 27, '看出來', 'kàn chū lái', '見て分かる・見抜く', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson11', 28, '談戀愛', 'tán liàn ài', '恋愛する・付き合う', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson11', 29, '安排', 'ān pái', '手配する・段取りする', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson11', 30, '安養院', 'ān yǎng yuàn', '老人ホーム', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson11', 31, '刷', 'shuā', '磨く・刷る', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson11', 32, '馬桶', 'mǎ tǒng', 'トイレの便器', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson11', 33, '育幼院', 'yù yòu yuàn', '孤児院・児童養護施設', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson11', 34, '照顧', 'zhào gù', '世話をする・介護する', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson11', 35, '刷牙', 'shuā yá', '歯を磨く', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson11', 36, '美術', 'měi shù', '美術・芸術', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson11', 37, '外邊', 'wài biān', '外・外側', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson11', 38, '檢查', 'jiǎn chá', '検査する・チェックする', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson11', 39, '處理', 'chǔ lǐ', '処理する・対処する', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson11', 40, '掛號', 'guà hào', '受付登録する・挂号', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson11', 41, '住院', 'zhù yuàn', '入院する', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson11', 42, '出院', 'chū yuàn', '退院する', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson11', 43, '等', 'děng', '待つ・など', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson11', 44, '病房', 'bìng fáng', '病室・病棟', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson11', 45, '關心', 'guān xīn', '気にかける・心配する', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson11', 46, '收穫', 'shōu huò', '収穫・得るもの', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson11', 47, '極', 'jí', '非常に・極めて', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson11', 48, '重視', 'zhòng shì', '重視する・大切にする', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson11', 49, '美好', 'měi hǎo', '素晴らしい・美しい', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson11', 50, '未來', 'wèi lái', '未来・将来', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson11', 51, '成長', 'chéng zhǎng', '成長する', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson11', 52, '中', 'zhōng', '〜の中・〜のうちに', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson11', 53, '寶貴', 'bǎo guì', '貴重な・大切な', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson11', 54, '意義', 'yì yì', '意義・意味', '[]');

-- ============================================================
-- LESSON 12: 小職員? 大老闆?
-- ============================================================
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson12', 1, '職員', 'zhí yuán', '職員・社員', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson12', 2, '職業', 'zhí yè', '職業・仕事', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson12', 3, '研究所', 'yán jiū suǒ', '大学院', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson12', 4, '研究', 'yán jiū', '研究する', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson12', 5, '課程', 'kè chéng', 'カリキュラム・コース', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson12', 6, '通知', 'tōng zhī', '通知する・知らせる', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson12', 7, '廣告', 'guǎng gào', '広告・CM', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson12', 8, '設計', 'shè jì', 'デザインする・設計する', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson12', 9, '想法', 'xiǎng fǎ', '考え方・アイデア', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson12', 10, '聽力', 'tīng lì', 'リスニング・聴力', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson12', 11, '會話', 'huì huà', '会話する', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson12', 12, '所', 'suǒ', '〜所（機関の量詞）', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson12', 13, '外語', 'wài yǔ', '外国語', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson12', 14, '學院', 'xué yuàn', '学院・カレッジ', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson12', 15, '哲學', 'zhé xué', '哲学', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson12', 16, '專業', 'zhuān yè', '専門・専攻', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson12', 17, '困難', 'kùn nán', '困難・難しい', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson12', 18, '起', 'qǐ', '起きる・始まる', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson12', 19, '助理', 'zhù lǐ', 'アシスタント・助手', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson12', 20, '向', 'xiàng', '〜に向けて・〜に', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson12', 21, '貿易', 'mào yì', '貿易・取引', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson12', 22, '保險', 'bǎo xiǎn', '保険', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson12', 23, '經理', 'jīng lǐ', 'マネージャー・部長', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson12', 24, '管理', 'guǎn lǐ', '管理する', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson12', 25, '員工', 'yuán gōng', '従業員・スタッフ', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson12', 26, '開會', 'kāi huì', '会議を開く', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson12', 27, '會', 'huì', '会・できる', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson12', 28, '加班', 'jiā bān', '残業する', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson12', 29, '研究', 'yán jiū', '研究する', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson12', 30, '難怪', 'nán guài', '難なく・道理で', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson12', 31, '退休', 'tuì xiū', '定年退職する', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson12', 32, '說真的', 'shuō zhēn de', '正直に言うと・本当に', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson12', 33, '再說', 'zài shuō', 'さらに言えば・それに', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson12', 34, '教書', 'jiāo shū', '教える・教職に就く', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson12', 35, '鄉下', 'xiāng xià', '田舎・農村', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson12', 36, '種', 'zhǒng', '種類・種を植える', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson12', 37, '剪', 'jiǎn', 'はさみで切る', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson12', 38, '都市', 'dū shì', '都市・都会', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson12', 39, '襯衫', 'chèn shān', 'シャツ・ワイシャツ', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson12', 40, '打工', 'dǎ gōng', 'アルバイトする', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson12', 41, '植物', 'zhí wù', '植物', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson12', 42, '個', 'gè', '〜個（量詞）', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson12', 43, '正式', 'zhèng shì', '正式な・フォーマル', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson12', 44, '存', 'cún', '貯金する・保存する', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson12', 45, '學費', 'xué fèi', '学費', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson12', 46, '做事', 'zuò shì', '仕事をする・行動する', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson12', 47, '成熟', 'chéng shú', '成熟した・大人な', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson12', 48, '強', 'qiáng', '強い・優れている', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson12', 49, '加強', 'jiā qiáng', '強化する・高める', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson12', 50, '服務生/服務員', 'fú wù shēng / fú wù yuán', 'ウェイター・サービス係', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson12', 51, '夜裡(裏)', 'yè lǐ', '夜・夜中に', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson12', 52, '樂觀', 'lè guān', '楽観的な', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson12', 53, '相信', 'xiāng xìn', '信じる', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson12', 54, '通知', 'tōng zhī', '通知・知らせ', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson12', 55, '敬', 'jìng', '敬う・敬意を示す', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson12', 56, '自我推薦', 'zì wǒ tuī jiàn', '自己推薦・自己PR', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson12', 57, '敬上', 'jìng shàng', '敬具（手紙の結語）', '[]');

-- ============================================================
-- LESSON 13: 我要買筆電
-- ============================================================
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson13', 1, '筆電(筆記型電腦)', 'bǐ diàn (bǐ jì xíng diàn nǎo)', 'ノートパソコン', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson13', 2, '產品', 'chǎn pǐn', '製品・商品', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson13', 3, '平板(平板電腦)', 'píng bǎn (píng bǎn diàn nǎo)', 'タブレット', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson13', 4, '差別', 'chā bié', '違い・差', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson13', 5, '說明', 'shuō míng', '説明する', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson13', 6, '功能', 'gōng néng', '機能・性能', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson13', 7, '輕', 'qīng', '軽い', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson13', 8, '出差', 'chū chāi', '出張する', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson13', 9, '不如', 'bù rú', '〜に及ばない・〜した方がよい', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson13', 10, '大多數', 'dà duō shù', '大多数・ほとんど', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson13', 11, '背包', 'bèi bāo', 'リュック・バックパック', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson13', 12, '不管', 'bù guǎn', '〜にかかわらず・関係なく', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson13', 13, '跟', 'gēn', '〜と・〜に従う', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson13', 14, '好用', 'hǎo yòng', '使いやすい・便利', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson13', 15, '新聞', 'xīn wén', 'ニュース・新聞', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson13', 16, '抱怨', 'bào yuàn', '不満を言う・文句を言う', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson13', 17, '電池', 'diàn chí', 'バッテリー・電池', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson13', 18, '正常', 'zhèng cháng', '正常な・普通', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson13', 19, '保證', 'bǎo zhèng', '保証する・確約する', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson13', 20, '修理', 'xiū lǐ', '修理する', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson13', 21, '恐怕', 'kǒng pà', 'おそらく・〜が心配だ', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson13', 22, '改天', 'gǎi tiān', 'またいつか・改めて', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson13', 23, '傳真機', 'chuán zhēn jī', 'ファックス機', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson13', 24, '傳真', 'chuán zhēn', 'ファックス・FAX', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson13', 25, '打折', 'dǎ zhé', '割引する・セール', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson13', 26, '超過', 'chāo guò', '超える・オーバーする', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson13', 27, '把握', 'bǎ wò', '確信・チャンスをつかむ', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson13', 28, '大約', 'dà yuē', 'だいたい・約', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson13', 29, '能夠', 'néng gòu', '〜できる・〜が可能', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson13', 30, '真', 'zhēn', '本当に・真', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson13', 31, '皮', 'pí', '皮・革', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson13', 32, '上班族', 'shàng bān zú', '会社員・ビジネスパーソン', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson13', 33, '保證書', 'bǎo zhèng shū', '保証書', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson13', 34, '打聽', 'dǎ tīng', '調べる・聞き込む', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson13', 35, '有道理', 'yǒu dào lǐ', '理にかなっている', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson13', 36, '道理', 'dào lǐ', '道理・理由', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson13', 37, '前', 'qián', '前・以前', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson13', 38, '後', 'hòu', '後・以降', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson13', 39, '認為', 'rèn wéi', '〜と思う・考える', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson13', 40, '比', 'bǐ', '〜より・比べる', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson13', 41, '價格', 'jià gé', '価格・値段', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson13', 42, '窮', 'qióng', '貧しい・お金がない', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson13', 43, '不見(了)', 'bú jiàn (le)', 'なくなった・見えない', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson13', 44, '愛惜', 'ài xī', '大切にする・惜しむ', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson13', 45, '零用錢', 'líng yòng qián', 'お小遣い', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson13', 46, '逼', 'bī', '強制する・追い詰める', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson13', 47, '省', 'shěng', '節約する・省く', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson13', 48, '答應', 'dā yìng', '承諾する・約束する', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson13', 49, '差(一)點兒', 'chà (yī) diǎnr', 'もう少しで〜するところ', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson13', 50, '糊塗', 'hú tu', 'ぼんやりした・うかつ', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson13', 51, '白', 'bái', '白・無駄に', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson13', 52, '麻煩', 'má fán', '面倒・迷惑', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson13', 53, '科技', 'kē jì', 'テクノロジー・科学技術', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson13', 54, '發現', 'fā xiàn', '発見する・気づく', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson13', 55, '解決', 'jiě jué', '解決する', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson13', 56, '光華商場', 'guāng huá shāng chǎng', '光華商場（台北の電気街）', '[]');
INSERT OR REPLACE INTO vocabulary (lesson_id, sort_order, hanzi, pinyin, translation_ja, examples_json) VALUES ('book2-lesson13', 57, '3C產品', '3C chǎn pǐn', '3C製品（家電・PC等）', '[]');

-- ============================================================
-- UPDATE VOCAB COUNTS
-- ============================================================
UPDATE lessons SET vocab_count = (SELECT COUNT(*) FROM vocabulary WHERE lesson_id = 'book2-lesson05') WHERE id = 'book2-lesson05';
UPDATE lessons SET vocab_count = (SELECT COUNT(*) FROM vocabulary WHERE lesson_id = 'book2-lesson06') WHERE id = 'book2-lesson06';
UPDATE lessons SET vocab_count = (SELECT COUNT(*) FROM vocabulary WHERE lesson_id = 'book2-lesson07') WHERE id = 'book2-lesson07';
UPDATE lessons SET vocab_count = (SELECT COUNT(*) FROM vocabulary WHERE lesson_id = 'book2-lesson08') WHERE id = 'book2-lesson08';
UPDATE lessons SET vocab_count = (SELECT COUNT(*) FROM vocabulary WHERE lesson_id = 'book2-lesson09') WHERE id = 'book2-lesson09';
UPDATE lessons SET vocab_count = (SELECT COUNT(*) FROM vocabulary WHERE lesson_id = 'book2-lesson10') WHERE id = 'book2-lesson10';
UPDATE lessons SET vocab_count = (SELECT COUNT(*) FROM vocabulary WHERE lesson_id = 'book2-lesson11') WHERE id = 'book2-lesson11';
UPDATE lessons SET vocab_count = (SELECT COUNT(*) FROM vocabulary WHERE lesson_id = 'book2-lesson12') WHERE id = 'book2-lesson12';
UPDATE lessons SET vocab_count = (SELECT COUNT(*) FROM vocabulary WHERE lesson_id = 'book2-lesson13') WHERE id = 'book2-lesson13';
